apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ml-lab.fullname" . }}-backend
subjects:
- kind: ServiceAccount
  name: {{ include "ml-lab.fullname" . }}-backend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ml-lab.fullname" . }}-backend
