{{- if .Values.integratedMinioStorage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ml-lab.fullname" . }}-minio-data
  labels:
    {{- include "ml-lab.labels" . | nindent 4 }}
    ctxy.deploymentType: "core"
    ctxy.deploymentName: "minio"
spec:
  accessModes: [ "ReadWriteOnce" ]
  {{- if .Values.integratedMinioStorage.storageClassName }}
  storageClassName: {{ .Values.integratedMinioStorage.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.integratedMinioStorage.storageSize }}
{{- end }}
